/* 
 * Easy!Appointments API
 *
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProviderRecordSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProviderRecordSettingsTests
    {
        // TODO uncomment below to declare an instance variable for ProviderRecordSettings
        //private ProviderRecordSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProviderRecordSettings
            //instance = new ProviderRecordSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProviderRecordSettings
        /// </summary>
        [Test]
        public void ProviderRecordSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProviderRecordSettings
            //Assert.IsInstanceOfType<ProviderRecordSettings> (instance, "variable 'instance' is a ProviderRecordSettings");
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Notifications'
        /// </summary>
        [Test]
        public void NotificationsTest()
        {
            // TODO unit test for the property 'Notifications'
        }
        /// <summary>
        /// Test the property 'CalendarView'
        /// </summary>
        [Test]
        public void CalendarViewTest()
        {
            // TODO unit test for the property 'CalendarView'
        }
        /// <summary>
        /// Test the property 'GoogleSync'
        /// </summary>
        [Test]
        public void GoogleSyncTest()
        {
            // TODO unit test for the property 'GoogleSync'
        }
        /// <summary>
        /// Test the property 'GoogleCalendar'
        /// </summary>
        [Test]
        public void GoogleCalendarTest()
        {
            // TODO unit test for the property 'GoogleCalendar'
        }
        /// <summary>
        /// Test the property 'GoogleToken'
        /// </summary>
        [Test]
        public void GoogleTokenTest()
        {
            // TODO unit test for the property 'GoogleToken'
        }
        /// <summary>
        /// Test the property 'SyncFutureDays'
        /// </summary>
        [Test]
        public void SyncFutureDaysTest()
        {
            // TODO unit test for the property 'SyncFutureDays'
        }
        /// <summary>
        /// Test the property 'SyncPastDays'
        /// </summary>
        [Test]
        public void SyncPastDaysTest()
        {
            // TODO unit test for the property 'SyncPastDays'
        }
        /// <summary>
        /// Test the property 'WorkingPlan'
        /// </summary>
        [Test]
        public void WorkingPlanTest()
        {
            // TODO unit test for the property 'WorkingPlan'
        }

    }

}
