/* 
 * Easy!Appointments API
 *
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SecretaryCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecretaryCollectionTests
    {
        // TODO uncomment below to declare an instance variable for SecretaryCollection
        //private SecretaryCollection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecretaryCollection
            //instance = new SecretaryCollection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecretaryCollection
        /// </summary>
        [Test]
        public void SecretaryCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecretaryCollection
            //Assert.IsInstanceOfType<SecretaryCollection> (instance, "variable 'instance' is a SecretaryCollection");
        }



    }

}
