# coding: utf-8

"""
    Easy!Appointments API

    These are the OpenAPI specs that describe the REST API of Easy!Appointments.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@easyappointments.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.categories_api import CategoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_categories_category_id_delete(self):
        """Test case for categories_category_id_delete

        Delete a category  # noqa: E501
        """
        pass

    def test_categories_category_id_get(self):
        """Test case for categories_category_id_get

        Get a category  # noqa: E501
        """
        pass

    def test_categories_category_id_put(self):
        """Test case for categories_category_id_put

        Update a category  # noqa: E501
        """
        pass

    def test_categories_get(self):
        """Test case for categories_get

        Get all categories  # noqa: E501
        """
        pass

    def test_categories_post(self):
        """Test case for categories_post

        Create a category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
