/*
 * Easy!Appointments API
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AdminRecordSettings model module.
 * @module model/AdminRecordSettings
 * @version 1.0.0
 */
export class AdminRecordSettings {
  /**
   * Constructs a new <code>AdminRecordSettings</code>.
   * @alias module:model/AdminRecordSettings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AdminRecordSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdminRecordSettings} obj Optional instance to populate.
   * @return {module:model/AdminRecordSettings} The populated <code>AdminRecordSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AdminRecordSettings();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('notifications'))
        obj.notifications = ApiClient.convertToType(data['notifications'], 'Boolean');
      if (data.hasOwnProperty('calendarView'))
        obj.calendarView = ApiClient.convertToType(data['calendarView'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
AdminRecordSettings.prototype.username = undefined;

/**
 * @member {String} password
 */
AdminRecordSettings.prototype.password = undefined;

/**
 * @member {Boolean} notifications
 */
AdminRecordSettings.prototype.notifications = undefined;

/**
 * @member {String} calendarView
 */
AdminRecordSettings.prototype.calendarView = undefined;

