/*
 * Easy!Appointments API
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AppointmentPayload model module.
 * @module model/AppointmentPayload
 * @version 1.0.0
 */
export class AppointmentPayload {
  /**
   * Constructs a new <code>AppointmentPayload</code>.
   * @alias module:model/AppointmentPayload
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AppointmentPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppointmentPayload} obj Optional instance to populate.
   * @return {module:model/AppointmentPayload} The populated <code>AppointmentPayload</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AppointmentPayload();
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], 'String');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
      if (data.hasOwnProperty('customerId'))
        obj.customerId = ApiClient.convertToType(data['customerId'], 'Number');
      if (data.hasOwnProperty('providerId'))
        obj.providerId = ApiClient.convertToType(data['providerId'], 'Number');
      if (data.hasOwnProperty('serviceId'))
        obj.serviceId = ApiClient.convertToType(data['serviceId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} start
 */
AppointmentPayload.prototype.start = undefined;

/**
 * @member {String} end
 */
AppointmentPayload.prototype.end = undefined;

/**
 * @member {String} location
 */
AppointmentPayload.prototype.location = undefined;

/**
 * @member {String} notes
 */
AppointmentPayload.prototype.notes = undefined;

/**
 * @member {Number} customerId
 */
AppointmentPayload.prototype.customerId = undefined;

/**
 * @member {Number} providerId
 */
AppointmentPayload.prototype.providerId = undefined;

/**
 * @member {Number} serviceId
 */
AppointmentPayload.prototype.serviceId = undefined;

