/*
 * Easy!Appointments API
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ServiceRecord model module.
 * @module model/ServiceRecord
 * @version 1.0.0
 */
export class ServiceRecord {
  /**
   * Constructs a new <code>ServiceRecord</code>.
   * @alias module:model/ServiceRecord
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ServiceRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceRecord} obj Optional instance to populate.
   * @return {module:model/ServiceRecord} The populated <code>ServiceRecord</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServiceRecord();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('availabilitiesType'))
        obj.availabilitiesType = ApiClient.convertToType(data['availabilitiesType'], 'String');
      if (data.hasOwnProperty('attendantsNumber'))
        obj.attendantsNumber = ApiClient.convertToType(data['attendantsNumber'], 'Number');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ServiceRecord.prototype.id = undefined;

/**
 * @member {String} name
 */
ServiceRecord.prototype.name = undefined;

/**
 * @member {Number} duration
 */
ServiceRecord.prototype.duration = undefined;

/**
 * @member {Number} price
 */
ServiceRecord.prototype.price = undefined;

/**
 * @member {String} currency
 */
ServiceRecord.prototype.currency = undefined;

/**
 * @member {String} location
 */
ServiceRecord.prototype.location = undefined;

/**
 * @member {String} description
 */
ServiceRecord.prototype.description = undefined;

/**
 * @member {String} availabilitiesType
 */
ServiceRecord.prototype.availabilitiesType = undefined;

/**
 * @member {Number} attendantsNumber
 */
ServiceRecord.prototype.attendantsNumber = undefined;

/**
 * @member {Number} categoryId
 */
ServiceRecord.prototype.categoryId = undefined;

