/*
 * Easy!Appointments API
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SettingRecord model module.
 * @module model/SettingRecord
 * @version 1.0.0
 */
export class SettingRecord {
  /**
   * Constructs a new <code>SettingRecord</code>.
   * @alias module:model/SettingRecord
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SettingRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SettingRecord} obj Optional instance to populate.
   * @return {module:model/SettingRecord} The populated <code>SettingRecord</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SettingRecord();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
SettingRecord.prototype.name = undefined;

/**
 * @member {String} value
 */
SettingRecord.prototype.value = undefined;

