/*
 * Easy!Appointments API
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EasyappointmentsApi);
  }
}(this, function(expect, EasyappointmentsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EasyappointmentsApi.AppointmentsApi();
  });

  describe('(package)', function() {
    describe('AppointmentsApi', function() {
      describe('appointmentsAppointmentIdDelete', function() {
        it('should call appointmentsAppointmentIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for appointmentsAppointmentIdDelete call
          /*

          instance.appointmentsAppointmentIdDelete(appointmentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('appointmentsAppointmentIdGet', function() {
        it('should call appointmentsAppointmentIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for appointmentsAppointmentIdGet call and complete the assertions
          /*

          instance.appointmentsAppointmentIdGet(appointmentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.AppointmentRecord);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('appointmentsAppointmentIdPut', function() {
        it('should call appointmentsAppointmentIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for appointmentsAppointmentIdPut call and complete the assertions
          /*

          instance.appointmentsAppointmentIdPut(body, appointmentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.AppointmentRecord);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('appointmentsGet', function() {
        it('should call appointmentsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for appointmentsGet call and complete the assertions
          /*
          var opts = {};

          instance.appointmentsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.AppointmentCollection);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('appointmentsPost', function() {
        it('should call appointmentsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for appointmentsPost call and complete the assertions
          /*

          instance.appointmentsPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.AppointmentRecord);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
