/*
 * Easy!Appointments API
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EasyappointmentsApi);
  }
}(this, function(expect, EasyappointmentsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EasyappointmentsApi.ProvidersApi();
  });

  describe('(package)', function() {
    describe('ProvidersApi', function() {
      describe('providersGet', function() {
        it('should call providersGet successfully', function(done) {
          // TODO: uncomment, update parameter values for providersGet call and complete the assertions
          /*
          var opts = {};

          instance.providersGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.ProviderCollection);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('providersPost', function() {
        it('should call providersPost successfully', function(done) {
          // TODO: uncomment, update parameter values for providersPost call and complete the assertions
          /*

          instance.providersPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.ProviderRecord);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('providersProviderIdDelete', function() {
        it('should call providersProviderIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for providersProviderIdDelete call
          /*

          instance.providersProviderIdDelete(providerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('providersProviderIdGet', function() {
        it('should call providersProviderIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for providersProviderIdGet call and complete the assertions
          /*

          instance.providersProviderIdGet(providerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.ProviderRecord);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('providersProviderIdPut', function() {
        it('should call providersProviderIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for providersProviderIdPut call and complete the assertions
          /*

          instance.providersProviderIdPut(body, providerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EasyappointmentsApi.ProviderRecord);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
