/*
 * Easy!Appointments API
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ErrorResponse} from '../model/ErrorResponse';
import {SettingCollection} from '../model/SettingCollection';
import {SettingPayload} from '../model/SettingPayload';
import {SettingRecord} from '../model/SettingRecord';

/**
* Settings service.
* @module api/SettingsApi
* @version 1.0.0
*/
export class SettingsApi {

    /**
    * Constructs a new SettingsApi. 
    * @alias module:api/SettingsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the settingsGet operation.
     * @callback moduleapi/SettingsApi~settingsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettingCollection{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all settings
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.length 
     * @param {String} opts.sort 
     * @param {String} opts.q 
     * @param {String} opts.fields 
     * @param {String} opts._with 
     * @param {module:api/SettingsApi~settingsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    settingsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'page': opts['page'],'length': opts['length'],'sort': opts['sort'],'q': opts['q'],'fields': opts['fields'],'with': opts['_with']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth', 'BearerToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SettingCollection;

      return this.apiClient.callApi(
        '/settings', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the settingsSettingNameGet operation.
     * @callback moduleapi/SettingsApi~settingsSettingNameGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettingRecord{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a setting
     * @param {String} settingName 
     * @param {module:api/SettingsApi~settingsSettingNameGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    settingsSettingNameGet(settingName, callback) {
      
      let postBody = null;
      // verify the required parameter 'settingName' is set
      if (settingName === undefined || settingName === null) {
        throw new Error("Missing the required parameter 'settingName' when calling settingsSettingNameGet");
      }

      let pathParams = {
        'settingName': settingName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth', 'BearerToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SettingRecord;

      return this.apiClient.callApi(
        '/settings/{settingName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the settingsSettingNamePut operation.
     * @callback moduleapi/SettingsApi~settingsSettingNamePutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettingRecord{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a setting
     * @param {module:model/SettingPayload} body 
     * @param {String} settingName 
     * @param {module:api/SettingsApi~settingsSettingNamePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    settingsSettingNamePut(body, settingName, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling settingsSettingNamePut");
      }
      // verify the required parameter 'settingName' is set
      if (settingName === undefined || settingName === null) {
        throw new Error("Missing the required parameter 'settingName' when calling settingsSettingNamePut");
      }

      let pathParams = {
        'settingName': settingName
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth', 'BearerToken'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SettingRecord;

      return this.apiClient.callApi(
        '/settings/{settingName}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}