<?php
/**
 * CustomersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Easy!Appointments API
 *
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * CustomersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for customersCustomerIdDelete
     *
     * Delete a customer.
     *
     */
    public function testCustomersCustomerIdDelete()
    {
    }

    /**
     * Test case for customersCustomerIdGet
     *
     * Get a customer.
     *
     */
    public function testCustomersCustomerIdGet()
    {
    }

    /**
     * Test case for customersCustomerIdPut
     *
     * Update a customer.
     *
     */
    public function testCustomersCustomerIdPut()
    {
    }

    /**
     * Test case for customersGet
     *
     * Get all customers.
     *
     */
    public function testCustomersGet()
    {
    }

    /**
     * Test case for customersPost
     *
     * Create a customer.
     *
     */
    public function testCustomersPost()
    {
    }
}
