=begin
#Easy!Appointments API

#These are the OpenAPI specs that describe the REST API of Easy!Appointments.

OpenAPI spec version: 1.0.0
Contact: info@easyappointments.org
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AdminsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AdminsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AdminsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdminsApi' do
    it 'should create an instance of AdminsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AdminsApi)
    end
  end

  # unit tests for admins_admin_id_delete
  # Delete an admin
  # @param admin_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'admins_admin_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admins_admin_id_get
  # Get an admin
  # @param admin_id 
  # @param [Hash] opts the optional parameters
  # @return [AdminRecord]
  describe 'admins_admin_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admins_admin_id_put
  # Update an admin
  # @param body 
  # @param admin_id 
  # @param [Hash] opts the optional parameters
  # @return [AdminRecord]
  describe 'admins_admin_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admins_get
  # Get all admins
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :length 
  # @option opts [String] :sort 
  # @option opts [String] :q 
  # @option opts [String] :fields 
  # @option opts [String] :with 
  # @return [AdminCollection]
  describe 'admins_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admins_post
  # Create an admin
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [AdminRecord]
  describe 'admins_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
