=begin
#Easy!Appointments API

#These are the OpenAPI specs that describe the REST API of Easy!Appointments.

OpenAPI spec version: 1.0.0
Contact: info@easyappointments.org
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AvailabilitiesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AvailabilitiesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AvailabilitiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AvailabilitiesApi' do
    it 'should create an instance of AvailabilitiesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AvailabilitiesApi)
    end
  end

  # unit tests for availabilities_get
  # Gets availability
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :provider_id 
  # @option opts [Integer] :service_id 
  # @option opts [String] :date 
  # @return [Availabilities]
  describe 'availabilities_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
