=begin
#Easy!Appointments API

#These are the OpenAPI specs that describe the REST API of Easy!Appointments.

OpenAPI spec version: 1.0.0
Contact: info@easyappointments.org
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ProvidersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProvidersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ProvidersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProvidersApi' do
    it 'should create an instance of ProvidersApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ProvidersApi)
    end
  end

  # unit tests for providers_get
  # Get all providers
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :length 
  # @option opts [String] :sort 
  # @option opts [String] :q 
  # @option opts [String] :fields 
  # @option opts [String] :with 
  # @return [ProviderCollection]
  describe 'providers_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for providers_post
  # Create a provider
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ProviderRecord]
  describe 'providers_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for providers_provider_id_delete
  # Delete a provider
  # @param provider_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'providers_provider_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for providers_provider_id_get
  # Get a provider
  # @param provider_id 
  # @param [Hash] opts the optional parameters
  # @return [ProviderRecord]
  describe 'providers_provider_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for providers_provider_id_put
  # Update a provider
  # @param body 
  # @param provider_id 
  # @param [Hash] opts the optional parameters
  # @return [ProviderRecord]
  describe 'providers_provider_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
