/* 
 * Easy!Appointments API
 *
 * These are the OpenAPI specs that describe the REST API of Easy!Appointments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@easyappointments.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ServicesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ServicesApiTests
    {
        private ServicesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ServicesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ServicesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ServicesApi
            //Assert.IsInstanceOfType(typeof(ServicesApi), instance, "instance is a ServicesApi");
        }

        /// <summary>
        /// Test ServicesGet
        /// </summary>
        [Test]
        public void ServicesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? length = null;
            //string sort = null;
            //string q = null;
            //string fields = null;
            //string with = null;
            //var response = instance.ServicesGet(page, length, sort, q, fields, with);
            //Assert.IsInstanceOf<ServiceCollection> (response, "response is ServiceCollection");
        }
        /// <summary>
        /// Test ServicesPost
        /// </summary>
        [Test]
        public void ServicesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ServicePayload body = null;
            //var response = instance.ServicesPost(body);
            //Assert.IsInstanceOf<ServiceRecord> (response, "response is ServiceRecord");
        }
        /// <summary>
        /// Test ServicesServiceIdDelete
        /// </summary>
        [Test]
        public void ServicesServiceIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? serviceId = null;
            //instance.ServicesServiceIdDelete(serviceId);
            
        }
        /// <summary>
        /// Test ServicesServiceIdGet
        /// </summary>
        [Test]
        public void ServicesServiceIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? serviceId = null;
            //var response = instance.ServicesServiceIdGet(serviceId);
            //Assert.IsInstanceOf<ServiceRecord> (response, "response is ServiceRecord");
        }
        /// <summary>
        /// Test ServicesServiceIdPut
        /// </summary>
        [Test]
        public void ServicesServiceIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ServicePayload body = null;
            //int? serviceId = null;
            //var response = instance.ServicesServiceIdPut(body, serviceId);
            //Assert.IsInstanceOf<ServiceRecord> (response, "response is ServiceRecord");
        }
    }

}
